### PR TITLE
Change round start message

### PR DESCRIPTION
**Pull request by Geekid812**
This is the associated PR for #175. Feel free to discuss there if the message should be changed.

### CODE REVIEW

**Comment by Ze-Rax** [comment]
Ellipsis (...) would be out of place, as it's not used elsewhere iirc. Also there's nothing happening in the background / no process, so I feel like it's semantically out of place, too.
I would just go for
> Round X start

**Comment by Geekid812** [comment]
Nadeo's Warmup lib has the warmup end message: "End of warmup, match starting...", yet nothing happens in the background there as well. Ellipsis can be used in a context when something is happening soon, so it might as well fit here.

Most importantly, big messages can be understood as if somebody said that sentence. Most other messages already have punctuation, with the exception of "WarmUp (End)" and "Overtime". In this case, it can make sense to say "we are in the warmup/in overtime" whereas it wouldn't make sense for round start: "this is the first round start". You would rather hear: "the first round is starting".

That is my reasoning, however I would like to hear what @reaby and @Rxelux have to say of this. It's not a very important change but I would like to hear what everyone's opinion is.

**Comment by reaby** [comment]
I agree with ze-rax. I think the messages should be simple and clean like:  `Round {number} Start` would be enough, or something like this.

**Review by Ze-Rax — APPROVED** [review]
The request to add the the round number to the message is fullfilled.

We may talk about rewriting all messages in general to comply with some kind of standard/convention in the future.

**Pull request merged**
