### PR TITLE
Teamskins

### PR DESCRIPTION
**Pull request by reaby**

### CODE REVIEW

**Comment by reaby** [comment]
Note: this propably needs to be merged before menu!

**Comment by Ze-Rax** [comment]
Suggestions:

Maybe we should integrate these changes into the FlagRush_Teams library. Have a function there to loads the skins and save the IDs, essentially what you're doing in  `***Match_LoadItems***` but instead call `FlagRush_Teams::LoadSkins` there. In `FlagRush_Teams::Init` assign the skins to the teams (`declare Ident SkinId for Teams[X]; SkinId = G_TeamSkins[X]`), then in `InitPlayer` check `if (S_UseTeamSkins)` and use the skins from `Teams[X]`. Then we can also use the declare-for-team in the MVP screen.

Reason:
- Separation of concerns. This is team related and should therefore be part of `FlagRush_Teams`
- In the future if we wanna support multiple skins under certain team specific conditions (Teamcolor? Teamname?) its easier to add new skins and adjust the assignment in that library.
- DRY: No need to define the skins in the Gamemode AND the MVP screen. This way we only define it once. And who know where else they would be used in the future.

**Comment by Ze-Rax** [comment]
Text on the back might not be readable due to usage of team color.
`Scripts\Libs\Nadeo\ModeLibs\Common\Clans_Common.Script.txt` contains configurations for the animal clan styling. This also includes a `ForegroundColor` (which is either black or white, depending on the car color around the trigram), we should maybe use these values for the trigrams then if we're forcing the team colors.

**Comment by reaby** [comment]
Did not used the Clans_Common script, instead i defined color for the dossard.
Took inconsideration suggested changes.

**Review by Ze-Rax — APPROVED** [review]

**Pull request merged**
